before_script:
  - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD

stages:
  - build_prod
  - build_dev
  - deploy_prod
  - deploy_dev

build_image_prod:
  stage: build_prod
  image: registry.uicgroup.tech/devops/docker:dind
  before_script:
    - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD
  script:
    - make vars-input KEYS=$KEYS
    - make build-image TAG=$CI_PIPELINE_IID SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=latest
    - make push-image TAG=$CI_PIPELINE_IID SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=latest
  only:
    - master

deploy_image_prod:
  stage: deploy_prod
  image: registry.uicgroup.tech/devops/docker:1.0
  before_script:
    - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD
  script:
    - docker service update --with-registry-auth --image registry.uicgroup.tech/tmi/tift-frontend:$CI_PIPELINE_IID 'tift_frontend'
  only:
    - master
  tags: 
    - tift-prod

build_image:
  stage: build_dev
  image: registry.uicgroup.tech/devops/docker:dind
  before_script:
    - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD
  script:
    - make vars-input KEYS=$DEV_KEYS
    - make build-image TAG=$CI_PIPELINE_IID SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=dev
    - make push-image TAG=$CI_PIPELINE_IID SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=dev
  only:
    - dev

deploy:
  stage: deploy_dev
  image: registry.uicgroup.tech/devops/docker:1.0
  before_script:
    - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD
  script:
    - docker pull registry.uicgroup.tech/tmi/tift-frontend:$CI_PIPELINE_IID
    - docker rm -f tift-frontend
    - docker run --name tift-frontend -d -p 3079:3000 --restart always registry.uicgroup.tech/tmi/tift-frontend:$CI_PIPELINE_IID
  only:
    - dev
  tags: 
    - hbs-academy
    
